- name: Archive dir
  file:
    path: '{{ data_dir }}/../data_archive'
    state: directory

- name: Check archive {{ archive_url }}
  stat:
    path: '{{ data_dir }}/../data_archive/{{ archive_url | basename }}'
  register: archive_exists

- name: Download archive {{ archive_url }}
  get_url:
    url: '{{ archive_url }}'
    dest: '{{ data_dir }}/archive'
  when: not archive_exists.stat.exists

- name: Extract archive {{ archive_url }}
  unarchive:
    src: '{{ data_dir }}/../data_archive/{{ archive_url | basename }}'
    dest: '{{ data_dir }}'
